### PR TITLE
PBI238 - Fix VideoCallClient's startCall method

### PR DESCRIPTION
**Pull request by bsonntag**
Fixes `VideoCallClient#startCall()` method and adds tests for it.

### CODE REVIEW

**Comment by bsonntag** [comment]
@DanielMor and @Mickael24 please review.

**Comment by bsonntag** [comment]
This is wrong.

**Comment by bsonntag** [comment]
Actually, it was OK.
@Mickael24 and @DanielMor please review.

**Comment by Mickael24** [comment]
👍

**Pull request merged**
