### PR TITLE
PBI238 - Updates login

### PR DESCRIPTION
**Pull request by bsonntag**
Renames `register()` to `login()`.
Updates message names.

### CODE REVIEW

**Comment by bsonntag** [comment]
@DanielMor and @Mickael24 please review.

**Comment by bsonntag** [comment]
I still need to update the tests.

**Comment by bsonntag** [comment]
@DanielMor and @Mickael24 please review.

**Comment by bsonntag** [comment]
@DanielMor and @Mickael24 please?

**Comment by Mickael24** [comment]
👍

**Comment by DanielMor** [comment]
👍

**Pull request merged**
